// <auto-generated />
using System;
using Infrastructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(DAMDbContext))]
    [Migration("20250317090525_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Asset", b =>
                {
                    b.Property<int>("BlobID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlobID"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("FileSizeInKB")
                        .HasColumnType("float");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjectID")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("BlobID");

                    b.HasIndex("ProjectID");

                    b.HasIndex("UserID");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("Core.Entities.AssetMetadata", b =>
                {
                    b.Property<int>("BlobID")
                        .HasColumnType("int");

                    b.Property<int>("FieldID")
                        .HasColumnType("int");

                    b.Property<string>("FieldValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BlobID", "FieldID");

                    b.HasIndex("FieldID");

                    b.ToTable("AssetMetadata");
                });

            modelBuilder.Entity("Core.Entities.AssetTag", b =>
                {
                    b.Property<int>("BlobID")
                        .HasColumnType("int");

                    b.Property<int>("TagID")
                        .HasColumnType("int");

                    b.HasKey("BlobID", "TagID");

                    b.HasIndex("TagID");

                    b.HasIndex("BlobID", "TagID");

                    b.ToTable("AssetTags");
                });

            modelBuilder.Entity("Core.Entities.Log", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("LogID");

                    b.HasIndex("UserID");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Core.Entities.MetadataField", b =>
                {
                    b.Property<int>("FieldID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FieldID"));

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FieldType")
                        .HasColumnType("int");

                    b.Property<int?>("PaletteID")
                        .HasColumnType("int");

                    b.HasKey("FieldID");

                    b.HasIndex("PaletteID");

                    b.ToTable("MetadataFields");
                });

            modelBuilder.Entity("Core.Entities.Palette", b =>
                {
                    b.Property<int>("PaletteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaletteID"));

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.HasKey("PaletteID");

                    b.HasIndex("ProjectID")
                        .IsUnique();

                    b.ToTable("Palettes");
                });

            modelBuilder.Entity("Core.Entities.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectID");

                    b.HasIndex("Name");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Core.Entities.ProjectMembership", b =>
                {
                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("UserRole")
                        .HasColumnType("int");

                    b.HasKey("ProjectID", "UserID");

                    b.HasIndex("UserID");

                    b.ToTable("ProjectMemberships");
                });

            modelBuilder.Entity("Core.Entities.ProjectMetadataField", b =>
                {
                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<int>("FieldID")
                        .HasColumnType("int");

                    b.Property<string>("FieldValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.HasKey("ProjectID", "FieldID");

                    b.HasIndex("FieldID");

                    b.ToTable("ProjectMetadataFields");
                });

            modelBuilder.Entity("Core.Entities.ProjectTag", b =>
                {
                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<int>("TagID")
                        .HasColumnType("int");

                    b.HasKey("ProjectID", "TagID");

                    b.HasIndex("TagID");

                    b.HasIndex("ProjectID", "TagID");

                    b.ToTable("ProjectTags");
                });

            modelBuilder.Entity("Core.Entities.Tag", b =>
                {
                    b.Property<int>("TagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TagID");

                    b.HasIndex("Name");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Core.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Email = "userTest@example.com",
                            IsSuperAdmin = true,
                            LastUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "userTest"
                        });
                });

            modelBuilder.Entity("Core.Entities.Asset", b =>
                {
                    b.HasOne("Core.Entities.Project", "Project")
                        .WithMany("Assets")
                        .HasForeignKey("ProjectID");

                    b.HasOne("Core.Entities.User", "User")
                        .WithMany("Assets")
                        .HasForeignKey("UserID");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.AssetMetadata", b =>
                {
                    b.HasOne("Core.Entities.Asset", "Asset")
                        .WithMany("AssetMetadata")
                        .HasForeignKey("BlobID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.MetadataField", "MetadataField")
                        .WithMany("AssetMetadata")
                        .HasForeignKey("FieldID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("MetadataField");
                });

            modelBuilder.Entity("Core.Entities.AssetTag", b =>
                {
                    b.HasOne("Core.Entities.Asset", "Asset")
                        .WithMany("AssetTags")
                        .HasForeignKey("BlobID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Tag", "Tag")
                        .WithMany("AssetTags")
                        .HasForeignKey("TagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Core.Entities.Log", b =>
                {
                    b.HasOne("Core.Entities.User", "User")
                        .WithMany("Logs")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.MetadataField", b =>
                {
                    b.HasOne("Core.Entities.Palette", "Palette")
                        .WithMany("MetadataFields")
                        .HasForeignKey("PaletteID");

                    b.Navigation("Palette");
                });

            modelBuilder.Entity("Core.Entities.Palette", b =>
                {
                    b.HasOne("Core.Entities.Project", "Project")
                        .WithOne("Palette")
                        .HasForeignKey("Core.Entities.Palette", "ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Core.Entities.ProjectMembership", b =>
                {
                    b.HasOne("Core.Entities.Project", "Project")
                        .WithMany("ProjectMemberships")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.User", "User")
                        .WithMany("ProjectMemberships")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.ProjectMetadataField", b =>
                {
                    b.HasOne("Core.Entities.MetadataField", "MetadataField")
                        .WithMany("ProjectMetadataFields")
                        .HasForeignKey("FieldID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Project", "Project")
                        .WithMany("ProjectMetadataFields")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetadataField");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Core.Entities.ProjectTag", b =>
                {
                    b.HasOne("Core.Entities.Project", "Project")
                        .WithMany("ProjectTags")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Tag", "Tag")
                        .WithMany("ProjectTags")
                        .HasForeignKey("TagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Core.Entities.Asset", b =>
                {
                    b.Navigation("AssetMetadata");

                    b.Navigation("AssetTags");
                });

            modelBuilder.Entity("Core.Entities.MetadataField", b =>
                {
                    b.Navigation("AssetMetadata");

                    b.Navigation("ProjectMetadataFields");
                });

            modelBuilder.Entity("Core.Entities.Palette", b =>
                {
                    b.Navigation("MetadataFields");
                });

            modelBuilder.Entity("Core.Entities.Project", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Palette")
                        .IsRequired();

                    b.Navigation("ProjectMemberships");

                    b.Navigation("ProjectMetadataFields");

                    b.Navigation("ProjectTags");
                });

            modelBuilder.Entity("Core.Entities.Tag", b =>
                {
                    b.Navigation("AssetTags");

                    b.Navigation("ProjectTags");
                });

            modelBuilder.Entity("Core.Entities.User", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Logs");

                    b.Navigation("ProjectMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
